/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-building-af9782245c134c21ae0c8df7f57077e6
title: Office building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[38.42, -205.47, -0.05]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[-7.6, 120.13, 0]} rotation={[0, 0, 1.45]}>
            <group position={[-116.28, -36.77, 98.3]}>
              <group position={[46.8, 9.3, 0.7]}>
                <mesh
                  geometry={nodes.BLD_OFFICE_00_walls_exterior_0.geometry}
                  material={materials.walls_exterior}
                />
              </group>
            </group>
            <group position={[-104.78, -39.13, 102.73]}>
              <group position={[35.3, 11.66, -3.73]}>
                <mesh
                  geometry={nodes.BLD_OFFICE_01_glass_0.geometry}
                  material={materials.glass}
                />
              </group>
            </group>
            <group position={[-104.89, -39.13, 102.67]}>
              <group position={[35.41, 11.66, -3.97]}>
                <mesh
                  geometry={nodes.BLD_OFFICE_02_rams_0.geometry}
                  material={materials.rams}
                />
              </group>
            </group>
          </group>
          <group position={[15.51, 25.52, 111.44]}>
            <group position={[-125.89, -5.69, 71.04]}>
              <mesh
                geometry={nodes['BLD_OFFICE_03_Material_#17_0'].geometry}
                material={materials.Material_17}
              />
            </group>
          </group>
          <group position={[8.84, 31.05, 93.71]}>
            <group position={[-119.22, -11.22, 88.76]}>
              <mesh
                geometry={nodes.BLD_OFFICE_04_glass_0.geometry}
                material={materials.glass}
              />
            </group>
          </group>
          <group position={[13.57, 38.31, 102.73]} rotation={[0, 0, 1.45]}>
            <group position={[9.31, 3.1, -3.73]}>
              <mesh
                geometry={nodes.BLD_OFFICE_05_walls_BLD_OFFICE_05_0.geometry}
                material={materials.walls_BLD_OFFICE_05}
              />
            </group>
          </group>
          <group position={[19.31, 98.67, 102.73]}>
            <group position={[41.71, 17.63, 743.76]}>
              <mesh
                geometry={nodes.BLD_OFFICE_06_w2_0.geometry}
                material={materials.material}
              />
            </group>
          </group>
          <group
            position={[-61.39, 28.32, 133.82]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs02__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-39.35, 26.2, 116.37]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-5.55, -0.78, 7.8]}>
              <mesh
                geometry={nodes.office_chairs00_Color_007_0.geometry}
                material={materials.Color_007}
              />
              <mesh
                geometry={nodes.office_chairs00_Color_002_0.geometry}
                material={materials.Color_002}
              />
              <mesh
                geometry={nodes.office_chairs00_Color_003_0.geometry}
                material={materials.Color_003}
              />
              <mesh
                geometry={nodes.office_chairs00_Color_000_0.geometry}
                material={materials.Color_000}
              />
              <mesh
                geometry={nodes.office_chairs00_Color_001_0.geometry}
                material={materials.Color_001}
              />
              <mesh
                geometry={nodes.office_chairs00_FrontColor_0.geometry}
                material={materials.FrontColor}
              />
            </group>
          </group>
          <group
            position={[-82.41, 23.63, 118.26]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-4.69, -1.09, 10.73]}>
              <mesh
                geometry={nodes.office_chairs01_Color_007_0.geometry}
                material={materials.Color_007}
              />
              <mesh
                geometry={nodes.office_chairs01_Color_003_0.geometry}
                material={materials.Color_003}
              />
              <mesh
                geometry={nodes.office_chairs01_FrontColor_0.geometry}
                material={materials.FrontColor}
              />
              <mesh
                geometry={nodes.office_chairs01_Color_002_0.geometry}
                material={materials.Color_002}
              />
            </group>
          </group>
          <group
            position={[-27.27, 17.23, 134.89]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-6.53, -0.95, 10.4]}>
              <mesh
                geometry={nodes.office_chairs03_Color_001_0.geometry}
                material={materials.Color_001}
              />
              <mesh
                geometry={nodes.office_chairs03_Color_003_0.geometry}
                material={materials.Color_003}
              />
              <mesh
                geometry={nodes.office_chairs03_FrontColor_0.geometry}
                material={materials.FrontColor}
              />
              <mesh
                geometry={nodes.office_chairs03_Color_007_0.geometry}
                material={materials.Color_007}
              />
            </group>
          </group>
          <group
            position={[-121.63, 13.59, 145.04]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[-6.11, 6.11, 6.11]}
          >
            <group position={[-5.96, -2.37, 10.85]}>
              <mesh
                geometry={nodes.BLD_OFFICE_08_Color_007_0.geometry}
                material={materials.Color_007}
              />
              <mesh
                geometry={
                  nodes.BLD_OFFICE_08_Blinds_Roman_Hobbled_Blue_0.geometry
                }
                material={materials.Blinds_Roman_Hobbled_Blue}
              />
            </group>
          </group>
          <group position={[19.29, 83.07, 191.39]}>
            <group position={[41.72, 33.23, 655.11]}>
              <mesh
                geometry={nodes.BLD_OFFICE_09_w2_0.geometry}
                material={materials.material}
              />
            </group>
          </group>
          <group position={[19.29, 83.07, 14.08]}>
            <group position={[41.72, 33.23, 655.11]}>
              <mesh
                geometry={nodes.BLD_OFFICE_010_w2_0.geometry}
                material={materials.material}
              />
            </group>
          </group>
          <group
            position={[44.57, 15.5, 133.82]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs004__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 133.82]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs005__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[141.28, 16.56, 116.37]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-5.55, -0.78, 7.8]}>
              <mesh
                geometry={nodes.office_chairs006_Color_007_0.geometry}
                material={materials.Color_007}
              />
              <mesh
                geometry={nodes.office_chairs006_Color_002_0.geometry}
                material={materials.Color_002}
              />
              <mesh
                geometry={nodes.office_chairs006_Color_003_0.geometry}
                material={materials.Color_003}
              />
              <mesh
                geometry={nodes.office_chairs006_Color_000_0.geometry}
                material={materials.Color_000}
              />
              <mesh
                geometry={nodes.office_chairs006_Color_001_0.geometry}
                material={materials.Color_001}
              />
              <mesh
                geometry={nodes.office_chairs006_FrontColor_0.geometry}
                material={materials.FrontColor}
              />
            </group>
          </group>
          <group
            position={[-98.33, 22.42, 116.37]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-5.55, -0.78, 7.8]}>
              <mesh
                geometry={nodes.office_chairs007_Color_007_0.geometry}
                material={materials.Color_007}
              />
              <mesh
                geometry={nodes.office_chairs007_Color_002_0.geometry}
                material={materials.Color_002}
              />
              <mesh
                geometry={nodes.office_chairs007_Color_003_0.geometry}
                material={materials.Color_003}
              />
              <mesh
                geometry={nodes.office_chairs007_Color_000_0.geometry}
                material={materials.Color_000}
              />
              <mesh
                geometry={nodes.office_chairs007_Color_001_0.geometry}
                material={materials.Color_001}
              />
              <mesh
                geometry={nodes.office_chairs007_FrontColor_0.geometry}
                material={materials.FrontColor}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 116.1]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs012__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[82.55, 23.52, 116.1]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs013__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-51.69, 27.22, 98.38]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs017__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 98.38]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs018__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[45.89, 20.56, 98.38]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs019__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-44.02, 39.96, 80.65]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs023__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 80.65]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs024__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[83.88, 11.75, 80.65]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs025__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-47.75, 12.81, 62.93]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs029__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 62.93]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs030__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[38.69, 19.78, 62.93]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs031__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-60.32, 25.92, 45.21]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs035__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 45.21]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs036__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[75.36, 15.51, 45.21]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs037__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-55.31, 19.78, 27.49]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs041__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[-4.1, 22.23, 27.49]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs042__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
          <group
            position={[75.36, 15.51, 27.49]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={6.11}
          >
            <group position={[-1.88, -0.77, 6.29]}>
              <mesh
                geometry={nodes.office_chairs043__0.geometry}
                material={materials.office_chairs02__0}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
